1 descriptions
sparkoo/boxitory pull request #17
Opened 2017-09-04 11:06 UTC by sparkoo

#1 
read box's version descriptions from file beside boxes

2017-09-05 07:05 UTC, vtelensky requested changes

2017-09-05 07:05 UTC, vtelensky commented on src/main/java/cz/sparko/boxitory/App.java
> +import cz.sparko.boxitory.service.NoopDescriptionProvider;
I don't see that it would be used in the diff.

2017-09-05 07:05 UTC, vtelensky commented on src/main/java/cz/sparko/boxitory/service/FilesystemDescriptionProvider.java
> +                    .reduce((a, b) -> b);   // get last object
I don't undestand this reduction function. Maybe link with good explanation will help me. thx

2017-09-05 07:15 UTC, D3ryk commented
Also I don't see the doc file to be changed. Some info how to use the feature would be useful.

2017-09-05 07:17 UTC, sparkoo commented on src/main/java/cz/sparko/boxitory/service/FilesystemDescriptionProvider.java
> +                    .reduce((a, b) -> b);   // get last object
I want to take last element in stream. Stream in Java have just findFirst(), but not anything like findLast(). This reduce takes always second element, so at the end, just the last one remains and it's the last one. It's little hacky and I would like to find better solution, if there's any :( 
https://stackoverflow.com/a/27547525/1597741
https://www.leveluplunch.com/java/examples/find-last-element-java8-stream/

2017-09-06 09:11 UTC, sparkoo commented
review fixed

2017-09-06 15:23 UTC, vtelensky approved these changes

2017-09-06 18:06 UTC, merged